### ISSUE TITLE
setting up a clone with my own airtable 

### ISSUE THREAD

**Issue by ryandeussing** [schafnoir/meier-cider-public#1]
Hi Courtney, I came across this awesome project via the Cider Workshop group and am interested in setting up my own instance.

What can I do to make that as simple as possible for you (fork this repo, perhaps set up Airtable tables with matching attributes, give you access to both?). And what can I do to remunerate you for the help?

I'm a first-time fermenter with 25 gallons in my living room hanging out at 1.003 SG daring me to figure out what to do next. I  live in Maine, in an area _littered_ with 50-100+ year old trees that nobody harvests but me.  Plan is to spearhead a group of locals to help me both harvest and drink all the results.

**Comment by schafnoir** [comment]
Hi @ryandeussing - great to hear you're interested in the code, and sounds like a fun project to get to know (and drink) your local tree heritage! 

If you're comfortable with R, the easiest thing to do would be the following:

1. I can send you an invite to Airtable (if you don't already have an account). I'll get a $10 credit if you use the link I send, which is always nice. I can then make you a clone of my Airtable setup, and you'll see the clone of my Airtable base pop up in your Airtable workspace.
2. I will update the code in this public repo. I've done a bit more dev work on my private one, which I'd like to add in here - there are now some neat juice sugar/acid/tannin visualizations from individual trees.
3. You can then fork this repo, tweak the code to use your Airtable credentials, and you can publish your own version of the app with your own Shinyapps.io account (also free).

It may be helpful to touch base via Google Chat or Zoom to go over the Airtable structure I've made. I always enjoy chatting with folks interested in cider.

If you're not a regular R coder, then options are a little different. I would still clone the Airtable setup for you for free and chat with you to walk through the structure, and you could pay me to setup the Shiny app to work with your Airtables. The cost would depend on whether you want a straight clone (easiest for me), or whether you want to modify/customize. If the latter, I would need to work up an estimate; I took this route with a French guy who wanted a completely customized app for his new cider business in Bourgogne that just opened.

Another piece to think about - I have a form I've made with EpiCollect5 that I use with my iPhone to map and photograph individual trees. I wrote an R script to query the EpiCollect DB and download the associated photos, and the script then pushes the mapped tree records to Airtable. Images have to be uploaded manually. I find it really nice to use the iPhone GPS whenever I find a tree, and then the trees just pop up on the map in the Shiny app.

Shoot me a message at meiercider@gmail.com if you want to setup a Google Chat, or email outside of Git to discuss more.
